name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Black 
        run: python -m pip install git+https://github.com/psf/black
      - name: Lint
        run: black --check .
